name: GitHub Actions
run-name: ${{ github.actor }} is checking ${{ github.ref }} branch 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
  baseapp-core:
    uses: ./.github/workflows/project-workflow.yml
    with:
      project: baseapp-core
  baseapp-social-auth:
    uses: ./.github/workflows/project-workflow.yml
    with:
      project: baseapp-social-auth
  baseapp-auth:
    uses: ./.github/workflows/project-workflow.yml
    with:
      project: baseapp-auth
  baseapp-cloudflare-stream-field:
    uses: ./.github/workflows/project-workflow.yml
    with:
      project: baseapp-cloudflare-stream-field
  baseapp-payments:
    uses: ./.github/workflows/project-workflow.yml
    with:
      project: baseapp-payments
  baseapp-drf-view-action-permissions:
    uses: ./.github/workflows/project-workflow.yml
    with:
      project: baseapp-drf-view-action-permissions
  baseapp-email-templates:
    uses: ./.github/workflows/project-workflow.yml
    with:
      project: baseapp-email-templates
